export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_CATEGORY: "SET_CATEGORY",
    SELECTED_CATEGORY: "SELECTED_CATEGORY",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    INC_QUANTITY: "INC_QUANTITY",
    DEC_QUANTITY: "DEC_QUANTITY"
};

